Src/SBear.Web/ViewModels/ArticleViewModels/ArticleTypeViewModel.cs
using SBear.Service.Blog.Dtos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SBear.Web.ViewModels.ArticleViewModels
{
    public class ArticleTypeViewModel
    {
        public List<BlogArticleTypeDto> BlogArticleTypes { get; set; }
    }
}

Src/SBear.Web/Controllers/ArticleTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SBear.Service.Blog.Dtos;
using SBear.Service.Blog.IBlogService;
using SBear.Web.Filters;
using SBear.Web.ViewModels.ArticleViewModels;
using Microsoft.Extensions.Caching.Memory;

namespace SBear.Web.Controllers
{
    [CheckLoginAuthorize]
    public class ArticleTypeController : Controller
    {
        private readonly IBlogArticleTypeService _blogArticleType;
        private readonly IMemoryCache _cache;

        public ArticleTypeController(IBlogArticleTypeService blogArticleType, IMemoryCache memoryCache)
        {
            _blogArticleType = blogArticleType;
            _cache = memoryCache;
        }
        public IActionResult Index()
        {
            ArticleTypeViewModel articleTypeViewModel = new ArticleTypeViewModel();
            articleTypeViewModel.BlogArticleTypes = _blogArticleType.GetAllList();
            return View(articleTypeViewModel);
        }
        public IActionResult Create(string articleTypeName)
        {
            var blogArticleTypeDto = new BlogArticleTypeDto()
            {
                TypeName = articleTypeName
            };
            _blogArticleType.Insert(blogArticleTypeDto);
            return RedirectToAction("Index"); ;
        }
        public IActionResult Delete(long id)
        {
            _blogArticleType.Delete(id);
            _cache.Remove("cache_HomeSideBar");
            return RedirectToAction("Index"); ;
        }
    }
}

Src/SBear.Web/Views/ArticleType/Index.cshtml
@{
    ViewData["Title"] = "文章分类";
}
@section Css{
    <link href="~/lib/bootstrapValidator/dist/css/bootstrapValidator.css" rel="stylesheet" />
}
@model SBear.Web.ViewModels.ArticleViewModels.ArticleTypeViewModel
<div class="row" style="padding-top: 30px;">
    <div class="col-md-8">
        <form id="addArticleTypeForm" asp-controller="ArticleType" asp-action="Create" method="post" class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-2 control-label">文章类型</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" name="articleTypeName" placeholder="请输入文章类型">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">新建</button>
                </div>
            </div>
        </form>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>类型名称</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.BlogArticleTypes)
                {
                    <tr>
                        <td>@item.TypeName</td>
                        <td>@Html.ActionLink("删除", "Delete", new { id = item.Id })</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section Script{
    <script src="~/lib/bootstrapValidator/dist/js/bootstrapValidator.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#addArticleTypeForm").bootstrapValidator({
                message: 'This value is not valid',
                excluded: [":disabled"],//关键配置，表示只对于禁用域不进行验证，其他的表单元素都要验证
                feedbackIcons: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    "articleTypeName": {
                        validators: {
                            notEmpty: {
                                message: '文章类型不能为空！'
                            }
                        }
                    },
                }
            });
        });
    </script>
}