Src/SBear.Web/ViewModels/ArticleViewModels/ArticleViewModel.cs
using SBear.Service.Blog.Dtos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SBear.Web.ViewModels.ArticleViewModels
{
    public class ArticleViewModel
    {
        public ArticleActionEnum ArticleAction { get; set; }
        public BlogArticleDto BlogArticle { get; set; }
        public List<SelectListItem> BlogArticleTypes { get; set; }
    }
    public enum ArticleActionEnum
    {
        Add = 1,
        Edit = 2
    }
}

Src/SBear.Web/ViewModels/HomeViewModel/ArticleViewModel.cs
using SBear.Service.Blog.Dtos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SBear.Web.ViewModels.HomeViewModel
{
    public class ArticleViewModel : BlogArticleDto
    {
    }
}

Src/SBear.Web/ViewModels/WirteArticleViewModels/ArticleViewModel.cs
using SBear.Service.Blog.Dtos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SBear.Web.ViewModels.WirteArticleViewModels
{
    public class ArticleViewModel
    {
        public ArticleActionEnum ArticleAction { get; set; }
        public BlogArticleDto BlogArticle { get; set; }
        public List<SelectListItem> BlogArticleTypes { get; set; }
    }
    public enum ArticleActionEnum
    {
        Add = 1,
        Edit = 2
    }
}

Src/SBear.Web/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SBear.Service.Blog.IBlogService;
using SBear.Framework.Util;

namespace SBear.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IBlogArticleService _blogArticleService;
        public ArticleController(IBlogArticleService blogArticleService)
        {
            _blogArticleService = blogArticleService;
        }
        [Route("Article/{id}")]
        [HttpGet]
        public IActionResult Index(long id)
        {
            var vv = _blogArticleService.GetArticle(id);
            _blogArticleService.AddArticleView(id);
            ViewBag.Article = vv;
            return View();
        }
        [HttpDelete]
        public IActionResult Delete(long id)
        {
            _blogArticleService.Delete(id);



            return Content("Success");
        }
    }
}

Src/SBear.Web/ViewComponents/Home/HomeCardViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SBear.Web.ViewModels;
namespace SBear.Web.ViewComponents.Home
{
    public class HomeCardViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(CardViewModel cardViewModel)
        {
            return View(cardViewModel);
        }
    }
    public enum CardAciotnTypeEnum
    {
        AtricleEdit = 1,
        HomeIndex = 2,
        HomeSearch = 3,
        HomeCatgory = 4
    }
}

Src/SBear.Web/Views/Article/Index.cshtml
@using SBear.Web.ViewComponents.Home;
@{
    var article = ViewBag.Article;
    ViewData["Title"] = article.Title;
}
@section Css{
    <link href="~/lib/editor.md/css/editormd.preview.css" rel="stylesheet" />
    <link href="~/css/articlelook.css" rel="stylesheet" />
}
<div class="row">
    <div class="col-md-12">
        @await Component.InvokeAsync("HomeCard", new CardViewModel { CardAciotnType = CardAciotnTypeEnum.AtricleEdit, ArticleIdentityId = article.Id })
        <div>
            <div class="article-header">
                <h1 class="article-title">@article.Title</h1>
                <div class="article-meta">
                    <span>
                        发表于  @article.CreateDate &nbsp; | &nbsp; 分类于 <a href="@Url.Action("Index", "Category", new { id = article.BlogArticleType.Id })">@article.BlogArticleType.TypeName</a> &nbsp; | &nbsp; 阅读次数 : @article.Views
                    </span>
                </div>
            </div>
            <div id="editormdview">
                <textarea id="append-test" style="display:none;">@article.MarkDownContent.ToString()</textarea>
            </div>
        </div>
    </div>
</div>
@section Script{
    <script src="~/lib/editor.md/lib/marked.min.js"></script>
    <script src="~/lib/editor.md/lib/prettify.min.js"></script>
    <script src="~/lib/editor.md/lib/raphael.min.js"></script>
    <script src="~/lib/editor.md/lib/underscore.min.js"></script>
    <script src="~/lib/editor.md/lib/sequence-diagram.min.js"></script>
    <script src="~/lib/editor.md/lib/flowchart.min.js"></script>
    <script src="~/lib/editor.md/lib/jquery.flowchart.min.js"></script>
    <script src="~/lib/editor.md/editormd.js"></script>
    <script>
        $(function () {
            var wordsView = editormd.markdownToHTML("editormdview",
                {
                    htmlDecode: "style,script,iframe",  // you can filter tags decode
                    emoji: true,
                    taskList: true,
                    tex: true,  // 默认不解析
                    flowChart: true,  // 默认不解析
                    sequenceDiagram: true,  // 默认不解析
                });
        });
    </script>
}